"""Create the final FS22 ASM 8R Performance BR mod folder skeleton.

Run from the repository root:
  python modelagem/ASM-8R-PERF-BR/scripts/create_asm8r_mod_skeleton.py

The script creates placeholders only. It does not replace the I3D, textures or
store images generated by Blender/Giants Editor.
"""

from pathlib import Path
from textwrap import dedent
import argparse


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXPORT_DIR = PROJECT_ROOT / "export" / "FS22_ASM_8R_PERF_BR"


MOD_DESC_XML = """<?xml version="1.0" encoding="utf-8" standalone="no"?>
<modDesc descVersion="79">
    <author>AgroScriptModding</author>
    <version>1.0.0.0</version>
    <title>
        <en>ASM 8R Performance BR</en>
        <pt>ASM 8R Performance BR</pt>
    </title>
    <description>
        <en>John Deere 8R Performance BR prepared by AgroScriptModding.</en>
        <pt>John Deere 8R Performance BR preparado pela AgroScriptModding.</pt>
    </description>
    <iconFilename>store/icon_ASM_8R_PERF_BR.dds</iconFilename>
    <multiplayer supported="true"/>
    <storeItems>
        <storeItem xmlFilename="vehicles/ASM_8R_PERF_BR.xml"/>
    </storeItems>
</modDesc>
"""


VEHICLE_XML = """<?xml version="1.0" encoding="utf-8" standalone="no"?>
<vehicle type="tractor">
    <annotation>ASM-8R-PERF-BR final modeling package placeholder.</annotation>
    <storeData>
        <name>ASM 8R Performance BR</name>
        <specs>
            <neededPower>410</neededPower>
            <maxSpeed>50</maxSpeed>
        </specs>
        <functions>
            <function>$l10n_function_tractor</function>
        </functions>
        <image>store/store_ASM_8R_PERF_BR.dds</image>
        <price>485000</price>
        <dailyUpkeep>410</dailyUpkeep>
        <brand>JOHNDEERE</brand>
        <category>tractorsL</category>
    </storeData>
    <base>
        <filename>vehicles/ASM_8R_PERF_BR.i3d</filename>
        <size width="3.3" length="6.7" height="3.55"/>
    </base>
    <components>
        <component centerOfMass="0 0.95 0" solverIterationCount="10" mass="15500"/>
    </components>
    <wheels>
        <!-- Configure wheel nodes after I3D export. -->
    </wheels>
    <lights>
        <!-- Configure factory LED, ASM roof bar and auxiliary grille lights. -->
    </lights>
    <attacherJoints>
        <!-- Configure rear hitch, drawbar and PTO after Giants Editor setup. -->
    </attacherJoints>
</vehicle>
"""


README_EXPORT = """ASM 8R Performance BR - Export Folder

This folder is a delivery skeleton generated from the final modeling package.

Replace placeholders with final exported assets:
- vehicles/ASM_8R_PERF_BR.i3d
- textures/*.png or *.dds
- store/store_ASM_8R_PERF_BR.dds
- store/icon_ASM_8R_PERF_BR.dds

After replacing assets, configure the vehicle XML in Giants Editor and test in
Farming Simulator 22 first. FS25 adaptation should keep the same node naming
unless the target game changes schema requirements.
"""


TEXTURE_README = """Texture slots expected:

- asm8r_body_4k_baseColor / normal / metallic / roughness / glossiness / dirtWear
- asm8r_engine_chassis_4k_baseColor / normal / metallic / roughness / glossiness / dirtWear
- asm8r_wheels_tires_4k_baseColor / normal / metallic / roughness / glossiness / dirtWear
- asm8r_interior_4k_baseColor / normal / metallic / roughness / glossiness / emissive
- asm8r_lights_2k_baseColor / normal / emissive
- asm8r_decals_2k_baseColor / normal
"""


SOUND_README = """Sound setup placeholder.

Use this folder for engine, transmission, turbo and direct exhaust sound data
during the implementation phase. Modeling is already locked and should not be
changed by sound work.
"""


I3D_PLACEHOLDER = """ASM_8R_PERF_BR.i3d placeholder.

Export the final model from Blender/Giants Editor and replace this placeholder
with the real I3D file.
"""


STORE_PLACEHOLDER = """DDS placeholder.

Replace this text file with:
- store_ASM_8R_PERF_BR.dds
- icon_ASM_8R_PERF_BR.dds
"""


def build_files(export_dir):
    return {
        export_dir / "modDesc.xml": MOD_DESC_XML,
        export_dir / "README_EXPORT.txt": README_EXPORT,
        export_dir / "vehicles" / "ASM_8R_PERF_BR.xml": VEHICLE_XML,
        export_dir / "vehicles" / "ASM_8R_PERF_BR.i3d.placeholder.txt": I3D_PLACEHOLDER,
        export_dir / "textures" / "README.txt": TEXTURE_README,
        export_dir / "sounds" / "README.txt": SOUND_README,
        export_dir / "store" / "store_ASM_8R_PERF_BR.dds.placeholder.txt": STORE_PLACEHOLDER,
        export_dir / "store" / "icon_ASM_8R_PERF_BR.dds.placeholder.txt": STORE_PLACEHOLDER,
    }


def write_file(path, content, force=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        print(f"skip existing: {path}")
        return
    path.write_text(dedent(content).strip() + "\n", encoding="utf-8")
    print(f"created: {path}")


def main():
    parser = argparse.ArgumentParser(description="Create ASM 8R mod skeleton.")
    parser.add_argument("--output", type=Path, default=DEFAULT_EXPORT_DIR, help="Target export folder.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing placeholder files.")
    args = parser.parse_args()

    export_dir = args.output.resolve()
    for path, content in build_files(export_dir).items():
        write_file(path, content, args.force)

    print(f"FS22 mod skeleton ready: {export_dir}")


if __name__ == "__main__":
    main()
